global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  # Prometheus
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Node exporter 
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # Grafana
  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]

  # Wordpress
  - job_name: 'wordpress'
    static_configs:
      - targets: ['wordpress:80']
    metrics_path: '/slymetrics/metrics'
    authorization:
      type: Bearer
      credentials: 'f63ace1a40a31224f6877c0b0ddd756474e22c87f9eb55b9ec0696581c740837'
